export default {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_FAILED: 'LOGIN_FAILED',
    REGISTRATION_SUCCEEDED: 'REGISTRATION_SUCCEEDED',
    REGISTRATION_FAILED: 'REGISTRATION_FAILED',
    REGISTRATION_FORBIDDEN: 'REGISTRATION_FORBIDDEN'
}
