export default {
    FETCH_PROJECT: 'FETCH_PROJECT',
    FETCH_PROJECTS: 'FETCH_PROJECTS',
    CREATE_PROJECT_SUCCEEDED: 'CREATE_PROJECT_SUCCEEDED',
    CREATE_PROJECT_FAILED: 'CREATE_PROJECT_FAILED',
    EDIT_PROJECT_SUCCEEDED: 'CREATE_PROJECT_SUCCEEDED',
    EDIT_PROJECT_FAILED: 'CREATE_PROJECT_FAILED',
    DELETE_PROJECT_SUCCEEDED: 'CREATE_PROJECT_SUCCEEDED',
    DELETE_PROJECT_FAILED: 'CREATE_PROJECT_FAILED',
}
